Homework 3 with Pandas

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\A02047803\Desktop\DATA_5500_FA_26\hw3\TSLA_Full.csv")
df

           Date Close/Last    Volume      Open       High        Low
0    10/14/2026    $367.16  31001420   $371.16    $371.39    $363.82
1    10/13/2026    $375.23  18393040  $372.325    $377.05    $371.30
2    10/12/2026    $378.03  20244290  $382.605    $382.70    $377.58
3    10/09/2026    $382.70  38952430   $382.38    $388.56    $379.71
4    10/08/2026    $375.00  28394950   $374.12    $375.96  $368.0301
..          ...        ...       ...       ...        ...        ...
246  10/21/2025    $442.60  54412170  $445.755    $449.30    $442.05
247  10/20/2025    $447.43  63718970  $443.865    $449.80    $440.61
248  10/17/2025    $439.31  89331580   $425.50  $441.4558    $423.60
249  10/16/2025    $428.75  77189890   $434.73    $439.35  $421.3101
250  10/15/2025    $435.15  71558190   $434.90    $440.51  $426.3301

[251 rows x 6 columns]

In [7]:
df = df.iloc[::-1].reset_index(drop=True)
df

           Date Close/Last    Volume      Open       High        Low
0    10/15/2025    $435.15  71558190   $434.90    $440.51  $426.3301
1    10/16/2025    $428.75  77189890   $434.73    $439.35  $421.3101
2    10/17/2025    $439.31  89331580   $425.50  $441.4558    $423.60
3    10/20/2025    $447.43  63718970  $443.865    $449.80    $440.61
4    10/21/2025    $442.60  54412170  $445.755    $449.30    $442.05
..          ...        ...       ...       ...        ...        ...
246  10/08/2026    $375.00  28394950   $374.12    $375.96  $368.0301
247  10/09/2026    $382.70  38952430   $382.38    $388.56    $379.71
248  10/12/2026    $378.03  20244290  $382.605    $382.70    $377.58
249  10/13/2026    $375.23  18393040  $372.325    $377.05    $371.30
250  10/14/2026    $367.16  31001420   $371.16    $371.39    $363.82

[251 rows x 6 columns]

In [18]:
df["Close/Last"] = df["Close/Last"].replace("[$]", "", regex=True).astype(float)
df["Moving_avg"] = df["Close/Last"].shift(1).rolling(window=5).mean()
df.head(10)

,Date,Close/Last,Volume,Open,High,Low,Moving_avg
0,10/15/2025,435.15,71558190,$434.90,$440.51,$426.3301,NaN
1,10/16/2025,428.75,77189890,$434.73,$439.35,$421.3101,NaN
2,10/17/2025,439.31,89331580,$425.50,$441.4558,$423.60,NaN
3,10/20/2025,447.43,63718970,$443.865,$449.80,$440.61,NaN
4,10/21/2025,442.60,54412170,$445.755,$449.30,$442.05,NaN
5,10/22/2025,438.97,84023460,$443.45,$445.539,$429.00,438.648
6,10/23/2025,448.98,126709800,$420.00,$449.3999,$413.90,439.412
7,10/24/2025,433.72,94727770,$446.83,$451.68,$430.17,443.458
8,10/27/2025,452.42,105867500,$439.98,$460.16,$438.69,442.340
9,10/28/2025,460.55,80185670,$454.775,$467.00,$451.60,443.338

In [ ]:
stock           = 0
first_buy       = 0
total_profit    = 0

for i in range(len(df)):
    current_price = df.loc[i, "Close/Last"]
    average = df.loc[i, "Moving_avg"]

    if current_price < average * 0.98: #buy conditions
        pass

        # buy

        #update buy variable

        #update first_buy variable if this is the first time you buy

    elif current_price > average * 1.02: #sell conditions
        pass

        #sell

        #calculate profit of this individual trade

        #keep a running total of all profit

    else: 
        pass

        # do nothing this iteration

In [ ]:
print("total profit", total_profit)
print("% returns")
print("first buy", first_buy)