Lecture for October 13th, 2026

In [2]:
for i in range(10):
    print("hello")

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\A02047803\Desktop\DATA_5500_FA_26\in_class_code\top-10k-spotify-songs-2025-07.csv")
df

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
0,1,Die With A Smile,2plbrEY59IikOBgBGLjaoe,Lady Gaga|Bruno Mars,1HY2Jd0NmPuamShAr6KMms|0du5cEVh5yTK9QJze8zA0C,Die With A Smile,10FLjwfpbxLmW8c25Xyc2N,100,4:11,0,8/16/2024,single,USUM72409273,9
1,2,DtMF,3sK8wGT43QFpWrvNQsrQya,Bad Bunny,4q3ewBCX7sLwd24euuV69X,DeBÍ TiRAR MáS FOToS,5K79FLRUCSysQnVESLcTdb,98,3:57,1,1/5/2025,album,QMFMF2447070,3
2,3,BIRDS OF A FEATHER,6dOtVTDdiauQNBQEDOtlAB,Billie Eilish,6qqNVTkY8uBg9cP3Jd7DAH,HIT ME HARD AND SOFT,7aJuG4TFXa2hmE4z1yxc3n,98,3:30,0,5/17/2024,album,USUM72401994,7
3,4,Clean Baby Sleep White Noise (Loopable),0zirWZTcXBBwGsevrsIpvT,Dream Supplier|Baby Sleeps|Background White Noise,6Cqtx9fpxzggIMuKn0RGCp|48zEowASEXWsK6lgP1xotZ|...,Best White Noise For Sleeping Baby,0NGHR9zjS5eFFlqtClA9VV,97,2:22,0,4/29/2020,single,NLC8M2000219,2
4,5,BAILE INoLVIDABLE,2lTm559tuIvatlT1u0JYG2,Bad Bunny,4q3ewBCX7sLwd24euuV69X,DeBÍ TiRAR MáS FOToS,5K79FLRUCSysQnVESLcTdb,96,6:07,1,1/5/2025,album,QMFMF2447057,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,Gamesofluck,0rdWkO7ncrh1lrJGDmLq9L,Parcels,3oKRxpszQKUjjaHz388fVA,Gamesofluck,0ugE0qpkFDNLYFmNiUOOKA,70,5:48,0,10/28/2016,single,FRU701600048,4
9996,9997,Casio,44ZKnfWEkp7wPs035j4Tua,Jungle,59oA5WbbQvomJz2BuRG071,For Ever,5gYCZgmXzzWXxOCb9fMfBm,70,3:54,0,9/14/2018,album,GBBKS1800101,4
9997,9998,FANTASTIC BABY - Japanese ver.,26JeAi8xsSvLRoNsl9B8Js,BIGBANG,4Kxlr1PRlDKEB0ekOCyHgX,ALIVE,7p5rDiIXiv1IcEMThKwsaM,70,3:51,0,3/28/2012,album,JPB601211901,8
9998,9999,Miniskirt,6Yj8kVuVR3UPxx9r5eFEoV,AOA,54gWVQFHf8IIqbjxAoOarN,MINISKIRT,6esB2DBt46m38ZycDPsn8D,70,2:59,0,1/16/2014,single,KRA491400072,2
9999,10000,Backslide,6fNaHkjAxP6rI2sZhT7QJn,Twenty One Pilots,3YQKmKGau1PzlVlkL1iodx,Clancy,1KFWgQTw3EMTQebaaepVBI,70,3:00,0,5/24/2024,album,USAT22402064,133

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   rank          10000 non-null  int64
 1   track_name    10000 non-null  object
 2   track_id      10000 non-null  object
 3   artist_names  10000 non-null  object
 4   artist_ids    10000 non-null  object
 5   album_name    9999 non-null   object
 6   album_id      10000 non-null  object
 7   popularity    10000 non-null  int64
 8   duration      10000 non-null  object
 9   explicit      10000 non-null  int64
 10  release_date  10000 non-null  object
 11  album_type    10000 non-null  object
 12  isrc          10000 non-null  object
 13  copies        10000 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [11]:
for song in df["track_name"]:
    print(song)

Die With A Smile
DtMF
BIRDS OF A FEATHER
Clean Baby Sleep White Noise (Loopable)
BAILE INoLVIDABLE
Not Like Us
That’s So True
APT.
All The Stars (with SZA)
Sailor Song
WILDFLOWER
luther (with sza)
tv off (feat. lefty gunplay)
NUEVAYoL
Ordinary
Good Luck, Babe!
Abracadabra
EoO
VeLDÁ
VOY A LLeVARTE PA PR
Timeless (feat Playboi Carti)
like JENNIE
One Of The Girls (with JENNIE, Lily Rose Depp)
Te Quería Ver
Si Antes Te Hubiera Conocido
I Wanna Be Yours
blue
DENIAL IS A RIVER
Anxiety
EVIL J0RDAN
ME JALO
Beautiful Things
Iris
Yellow
Sweater Weather
See You Again (feat. Kali Uchis)
squabble up
NOKIA
Busy Woman
Like Him (feat. Lola Young)
Lose Control
Taste
Messy
RATHER LIE (with The Weeknd)
Locked out of Heaven
ROSONES
7 Dias
TATTOO
mi refe
The Night We Met
Every Breath You Take
Qué Pasaría...
No One Noticed
End of Beginning
KLOuFRENS
WELTiTA
The Days - NOTION Remix
Cry For Me
Revolving door
I Love You, I'm Sorry
Espresso
CHIHIRO
NADIE
When I Was Your Man
greedy
Tu Boda
ANXIETY (feat. Doechii)
Who
Morena
Por Esos Ojos
DOS DÍAS
LUNA
Blinding Lights
Dark Thoughts
Something Just Like This
Creep
The Scientist
Starboy
No. 1 Party Anthem
HUMBLE.
Night Changes
Perfect
Shape of You
A Sky Full of Stars
That's What I Like
No Pole
Khé?
Loco
BMF
30 For 30 (with Kendrick Lamar)
Headlock
Show Me Love
Snooze
Cruel Summer
The Giver
Presidente
Just the Way You Are
La Plena - W Sound 05
M&M
capaz (merengueton)
Gata Only
Imagínate
I Love You So
Feel It - From The Original Series “Invincible”
Lovers Rock
My Love Mine All Mine
Sweet Dreams (feat. Miguel)
Like That
As It Was
Dreams - 2004 Remaster
In the End
Viva La Vida
Feel Good Inc.
Numb
Mr. Brightside
Without Me
Apocalypse
Pink + White
Give Me Everything (feat. Nayer)
Swim
Do I Wanna Know?
Closer
lovely (with Khalid)
Stargazing
peekaboo (feat. azchike)
DIE TRYING
MILLION DOLLAR BABY
Sticky (feat. GloRilla, Sexyy Red & Lil Wayne)
The Door
toxic till the end
Pink Pony Club
Unwritten
Flowers
we can't be friends (wait for your love)
Bed Chem
MONA LISA
Sports car
Pika Pika
EL LOKERON
I'm The Problem
NIGHTS LIKE THIS
Kill Bill
505
I Remember Everything (feat. Kacey Musgraves)
Beanie
Mockingbird
FE!N (feat. Playboi Carti)
What Was I Made For? [From The Motion Picture "Barbie"]
Stick Season
Slow It Down
Gangsta's Paradise
Fix You
Sparks
Someone You Loved
White Ferrari
Take on Me
Sweet Child O' Mine
Africa
Everybody Wants To Rule The World
Unforgettable
Uptown Funk (feat. Bruno Mars)
One Dance
All of Me
goosebumps
Dandelions
Photograph
Wake Me Up
Believer
Counting Stars
Another Love
Born Again (feat. Doja Cat & RAYE)
PERFuMITO NUEVO
A Bar Song (Tipsy)
Carry You Home
Love Somebody
Bad Dreams
São Paulo (feat. Anitta)
Handlebars (feat. Dua Lipa)
PUSH 2 START
Garden Of Eden
Nonsense
Nobody Gets Me
traitor
I'm Good (Blue)
Juno
Please Please Please
CRUSH (with Travis Scott)
The Color Violet
Die For You
Cigarettes out the Window
Shut up My Moms Calling
Amapola
Love Me
Romantic Homicide
Parte & Choke
VITAMINA
En Privado
7-May
LA CANCIÓN
Can't Hold Us (feat. Ray Dalton)
TV
Pink Skies
Don't Stop Believin' (2022 Remaster)
Austin (Boots Stop Workin')
Feather
Heat Waves
Softcore
Dark Red
Guess featuring billie eilish
Stumblin' In
I Adore You (feat. Daecolm)
Q U E V A S H A C E R H O Y ?
Save Your Tears
Type Shit
Cinnamon Girl
The Cut That Always Bleeds
Thunderstruck
How You Remind Me
Somewhere Only We Know
Bring Me To Life
Can't Stop
Clocks
The Real Slim Shady
Promiscuous
Yeah! (feat. Lil Jon & Ludacris)
The Less I Know The Better
Circles
Shut Up and Dance
Young And Beautiful
Daddy Issues
Ransom
Sure Thing
No Role Modelz
Story of My Life
back to friends
Thinkin Bout You
Sign of the Times
Timber
Pumped Up Kicks
Lucid Dreams
Let Me Love You
Love On The Brain
There's Nothing Holdin' Me Back
The Hills
PRIDE.
ExtraL (feat. Doechii)
15 Minutes
Move
CAFé CON RON
EL CLúB
Indigo (feat. Avery Anna)
Sorry I'm Here For Someone Else
Water
Here With Me
when the party's over
Breakin' Dishes
deja vu
drivers license
Hips Don't Lie (feat. Wyclef Jean)
LUNCH
GOOD CREDIT (with Kendrick Lamar)
PHILLY (with Travis Scott)
Garam & Madu (Sakit Dadaku)
Payphone
Friends
ROSONES
Low Life (feat. The Weeknd)
Not Allowed
Bandida
ARE WE STILL FRIENDS?
Haegeum
Talking to the Moon
Oh Garota Eu Quero Você Só Pra Mim
Resenha do Arrocha
Mãe Solteira
Les
Dreams & Calmness
Deep Phase Noise 1
earthquake
PONTE LOKITA
DEPORTIVO
ESCAPATE
UWAIE
Under The Influence
Happier Than Ever
Say Yes To Heaven
Houdini
Toxicity
Chop Suey!
Tennessee Whiskey
M a k e I t T o T h e M o r n i n g
Something in the Orange
Ain't No Love In Oklahoma (From Twisters: The Album)
Shivers
the perfect pair
Cry
About You
Duvet
I Smoked Away My Brain (I'm God x Demons Mashup) (feat. Imogen Heap & Clams Casino)
LA PATRULLA
HIGHEST IN THE ROOM
Heather
In The Stars
Zombie
Linger
Fade Into You
Losing My Religion
Hotel California - 2013 Remaster
Highway to Hell
Have You Ever Seen The Rain
Heartless
Faint
Flashing Lights
Smack That
Watermelon Sugar
What Makes You Beautiful
Don't
The Nights
Ivy
I Want to Know What Love Is - 1999 Remaster
Dancing Queen
Why'd You Only Call Me When You're High?
Only Girl (In The World)
Time of Our Lives
Sex on Fire
Just Give Me a Reason (feat. Nate Ruess)
Say You Won't Let Go
Summer
Outside (feat. Ellie Goulding)
ocean eyes
Hymn for the Weekend
Stressed Out
DJ Got Us Fallin' In Love (feat. Pitbull)
Love The Way You Lie
Call Out My Name
Safe and Sound
Treat You Better
Paradise
Love Yourself
Sorry
Skyfall
Thunder
LOVE. FEAT. ZACARI.
NEW DROP
Too Sweet
The Sound of Silence - CYRIL Remix
Kisses (feat. bbyclose)
Real Man
TURiSTA
BOKeTE
KETU TeCRÉ
NISSAN ALTIMA
I Had Some Help (Feat. Morgan Wallen)
I miss you, I’m sorry
Call Me When You Break Up (with Gracie Abrams)
One Last Time
Always Remember Us This Way
How Bad Do U Want Me
Vanish Into You
vampire
Red Wine Supernova
cardigan
Toxic
a thousand years
TiK ToK
you broke me first
Bad Romance
Diet Pepsi
Lover
THE GREATEST
Emergence
TOXIC (with Skepta)
BACKD00R (feat. Kendrick Lamar & Jhené Aiko)
MOJO JOJO
HOT
Take Me To Church
Demons
Todo a Su Tiempo
Popular (with Playboi Carti & Madonna) - From The Idol Vol. 1 (Music from the HBO Original Series)
Maps
Sundress
20 Min
Baby
We Found Love
EARFQUAKE
Raanjhan (From "Do Patti")
El Mayor de los Ranas
Tubarões - Ao Vivo
Fui Mlk
tau mich auf
Wackelkontakt
Poker Face
The Way I Are
Solo
raining for hours
Y LLORO
Madonna
X (feat. Maluma & Ozuna) - Remix
Amigos? No.
Si No Quieres No
57
AY MAMÁ
Break from Toronto
Marilag
Love Hangover (feat. Dominic Fike)
everything i wanted
Car's Outside
Like a Stone
When It Rains It Pours
You Should Probably Leave
Cowgirls (feat. ERNEST)
Ghost
DEGENERE 👑 (feat. benny blanco)
Open Arms (feat. Travis Scott)
Freaks
snowfall
Je te laisserai des mots
Atlantis
Summertime Sadness
West Coast
Reflections
Bad Habit
The Spins
Heavy
Sex, Drugs, Etc.
Blue Hair
Falling Down - Bonus Track
WAIT FOR U (feat. Drake & Tems)
Fuck Love
Revenge
Standing Next to You
Money Trees
HOLLYWOOD
PERRO NEGRO
Too Many Nights (feat. Don Toliver & with Future)
flashes
Ojitos Lindos
Prada
I Don't Wanna Wait
4X4
TWENTIES
Here Comes The Sun - Remastered 2009
Riptide
Fast Car
Where the Wild Things Are
Everlong
No Surprises
Under the Bridge
Smells Like Teen Spirit
Kiss Me
Sultans Of Swing
I Was Made For Lovin' You
The Chain - 2004 Remaster
We Are The People
Californication
Seven Nation Army
How to Save a Life
Alright
One Step Closer
Ms. Jackson
Maneater
She Will Be Loved - Radio Mix
This Love
Gimme More
Till I Collapse
Happier
SICKO MODE
Memories
Streets
Beggin'
Sunsetz
K.
I'm Still Standing
Dancing In the Dark
Sweet Dreams (Are Made of This) - 2005 Remaster
Back In Black
Welcome To The Jungle
Low (feat. T-Pain)
Feel So Close - Radio Edit
Mask Off
S&M
Lost
Rude
Hey, Soul Sister
Passionfruit
I'm Not The Only One
Stitches
I Want It That Way
Try
Adventure of a Lifetime
I Like Me Better
I Was Never There
All Girls Are The Same
24K Magic
i like the way you kiss me
Black Friday (pretty like the sun)
The Emptiness Machine
we fell in love in october
Forever Young
Dirty Cash (Money Talks)
LA MuDANZA
I know love (feat. The Kid LAROI)
FXCK UP THE WORLD (feat. Future)
Soltera
Close To You
Fortnight (feat. Post Malone)
7 rings
i love you
Don’t Blame Me
Kiss Me More (feat. SZA)
Don't Stop The Music
Umbrella
Complicated
Casual
august
Shallow
Good Days
Easy On Me
happier
good 4 u
L’AMOUR DE MA VIE
HBA
WAKE UP F1LTHY (with Travis Scott)
FINE SHIT
RADAR
K POP
POP OUT
Bunga Maaf
Dusk Till Dawn (feat. Sia) - Radio Edit
Alibi (with Pabllo Vittar & Yseult)
Hard Times
Praise The Lord (Da Shine) (feat. Skepta)
Danza Kuduro
Again
nuts
Ishq Hai
Confident
You’re Gonna Go Far
Don't Start Now
Sei Que Tu Me Odeia
Descer
HOT TO GO!
Heartbeat
Just Dance
Winter Ahead (with PARK HYO SHIN)
Magnetic
Igloo
PIÉNSALO
Morena Canela
Primera Cita
telepatía
Borro Cassette
PELIGROSA
gervonta
COQUETA
Volver
Chiquita
RARI
No Me Conoce - Remix
Después De La 1
SI NO ES CONTIGO
sobelove
Frente al Mar
Es un Secreto
Dile
Infrunami
Smile
I Never Lie
It Will Rain
Broken Clocks
Novacane
Breakeven
Shameless
Ain't No Mountain High Enough
Way down We Go
Ma Meilleure Ennemie (from the series Arcane League of Legends)
Duality
Aerials
I WANNA BE YOUR SLAVE
Heading South
Beautiful Crazy
Wondering Why
Fortunate Son
Born With a Broken Heart
Evergreen
Glimpse of Us
Borderline
On Melancholy Hill
Chamber Of Reflection
My Kind of Woman
Brooklyn Baby
Something About You
Good Looking
Sunroof
Superpowers
Always
Scared To Start
Washing Machine Heart
Heart To Heart
Funk de Beleza - Slowed
FUNK DO BOUNCE (Slowed)
Bound 2
Violent Crimes
Hope
Moonlight
Seven (feat. Latto) (Explicit Ver.)
Runaway
Beauty And A Beat
family ties (with Kendrick Lamar)
one of wun
Trance (with Travis Scott & Young Thug)
God's Plan
Miles On It
Tití Me Preguntó
The Box
redrum
Thank You (Not So Bad)
Godzilla (feat. Juice WRLD)
Fat Juicy & Wet
LV Bag (feat. j-hope of BTS & Pharrell Williams)
Gang Baby
Break Stuff
Drops of Jupiter (Tell Me)
I Ain't Worried
Dance The Night - From Barbie The Album
Bitter Sweet Symphony - Remastered 2016
What Is Love - 7" Mix
Rocket Man (I Think It's Going To Be A Long, Long Time)
Don't Stop Me Now - Remastered 2011
Dream On
If I Ain't Got You
Take Me Out
What I've Done
The Reason
One Last Breath
Chasing Cars
Scar Tissue
Still D.R.E.
I Wonder
SexyBack (feat. Timbaland)
I Gotta Feeling
Empire State Of Mind
Superman
Hey Ya!
Gasolina
No Lie
Lost in the Fire (feat. The Weeknd)
Too Good At Goodbyes
Before You Go
Let Me Down Slowly
Sweet
International Love (feat. Chris Brown)
Reminder
Billie Jean
Could You Be Loved
Livin' On A Prayer
Bad At Love
two
Glue Song
Heathens
Happy - From "Despicable Me 2"
Cheerleader (Felix Jaehn Remix) - Radio Edit
Ho Hey
I Don’t Wanna Live Forever (Fifty Shades Darker)
Mirrors
Someone Like You
Set Fire to the Rain
Titanium (feat. Sia)
Budapest
Marry You
What Do You Mean?
Feel This Moment (feat. Christina Aguilera)
Thinking out Loud
Whatever It Takes
DNA.
Steal My Girl
Dreamin
TORE UP
Saturn
hey now (feat. dody6)
GIMME A HUG
Big Dawgs
St. Chroma (feat. Daniel Caesar)
Tweaker
PIToRRO DE COCO
We Hug Now
Ms. Whitman
Before You Leave Me
Burning Down
AMARGURA
It Must Have Been Love - From the Film "Pretty Woman"
Havana (feat. Young Thug)
I Wanna Dance with Somebody (Who Loves Me)
Anti-Hero
Shadow Of A Man
Zombieboy
Lush Life
Apple
Without Me
...Baby One More Time
Woman
favorite crime
the boy is mine
Good Graces
BLUE
WE NEED ALL DA VIBES (with Young Thug & Ty Dolla $ign)
TRIM (with Future)
I SEEEEEE YOU BABY BOI
CHARGE DEM HOES A FEE (with Future & Travis Scott)
Don’t Say You Love Me
welcome and goodbye
Sa Bawat Sandali
Jo Tum Mere Ho
Somebody That I Used To Know
LOS CUADROS
Ride Or Die, Pt. 2 (with Villano Antillano & Tokischa)
Don't Dream It's Over
7 Years
Animals
Cigarette Daydreams
Tek It
Telephones
Swimming Pools (Drank)
Star Shopping
NIGHTS LIKE THESE
Trap Queen
Mantra
Take Me to Church
Tak Ada Ujungnya
LOKERA
Rumah Ke Rumah
Took Her To The O
Mejores Jordans
Brown Eyed Girl
September
Balorda nostalgia
Levitating (feat. DaBaby)
Vidrado Em Você
Too Much
Me Ama Ou Me Larga - Ao Vivo
Barbie
Penélope Charmosa 2
MOTINHA 2.0 (Mete Marcha)
Nossas Fotos
Tibok
Is There Someone Else?
After The Storm (feat. Tyler, The Creator & Bootsy Collins)
For the First Time
Those Eyes
Valerie (feat. Amy Winehouse) - Version Revisited
Tattoo
Every Night White Noise
Loud Noise Sound
seasons
Teeth
Azul
Cuatro Babys (feat. Trap Capos, Noriel, Bryant Myers & Juhn)
Yo Vengo De La Nada
Parte & Choke (with Ryan Castro) - Remix
La Bachata
Extssy Model
NUEVA VIDA
TÚ NAME
Regalo De Dios
MIENTRAS DUERMES
ROCKSTAR
Tiroteo - Remix
Quevedo: Bzrp Music Sessions, Vol. 52
Hawái
El Perdedor
bunda 🍑
Feliz Cumpleaños Ferxxo
Se Preparó
SI NO ES CONTIGO - REMIX
Mírame
Cosas Pendientes
Ráfagas al Viento
Yo sé
el ingeniero
111
Columbia
Según Quién
QLONA
SE ME OLVIDA
Ese Vato No Te Queda
LINDA
A Mí
Ohnana
Ella Y Yo - Featuring Don Omar
Chandelier
Girls Just Want to Have Fun
Jhol
DRIP
LALA
Mi Vida Mi Muerte
Worst Way
Love
Perfect
Anchor
drunk text
Training Season
exes
run for the hills
You're Gonna Go Far, Kid
Wish You Were Here
Still into You
Killing In The Name
Whiskey Glasses
Lies Lies Lies
Rock and A Hard Place
Thinkin’ Bout Me
Paint It, Black
Bad Habits
Heart-Shaped Box
I Bet on Losing Dogs
Mr. Loverman
Brazil
Jealous
rises the moon
Margaret (feat. Bleachers)
Pain
i was all over her
Say My Name - Remix
Beautiful People
Sunflower - Spider-Man: Into the Spider-Verse
Everyday (feat. Rod Stewart, Miguel & Mark Ronson)
Father Stretch My Hands Pt. 1
Fashion Killa
LVL
Headlines
MOJABI GHOST
Sprinter
on one tonight
I KNOW ?
MY EYES
Creepin' (with The Weeknd & 21 Savage)
CARNIVAL
Still Into You
Somedays
fukumean
Ric Flair Drip (with Metro Boomin)
euphoria
Lovin On Me
Me Porto Bonito
Moscow Mule
After Hours
Big Poppa - 2005 Remaster
Cold Heart - PNAU Remix
STAY (with Justin Bieber)
Belong Together
Hypnotize - 2014 Remaster
California Love - Original Version
Hit 'Em Up - Single Version
Good Riddance (Time of Your Life)
Karma Police
November Rain
Wicked Game
Basket Case
All The Small Things
The Kids Aren't Alright
Come As You Are
Hold the Line
Vienna
Gimme! Gimme! Gimme! (A Man After Midnight)
Lovely Day
Another Brick in the Wall, Pt. 2
American Idiot
Replay
Walking On A Dream
The Middle
Kryptonite
Teenage Dirtbag
Kids
Last Resort
Back To Black
All Falls Down
Otherside
Look After You
Crazy In Love (feat. JAY-Z)
Rock Your Body
Lady - Hear Me Tonight
Can't Tell Me Nothing
Stronger
Say It Right
In Da Club
Temperature
Right Round
Young Dumb & Broke
Locked Away (feat. Adam Levine)
Centuries
Moves Like Jagger - Studio Recording From "The Voice" Performance
PILLOWTALK
Ophelia
Youngblood
Cake By The Ocean
Drive By
Attention
rockstar (feat. 21 Savage)
Waiting For Love
BUTTERFLY EFFECT
Wet Dreamz
Fast Car
Another One Bites The Dust - Remastered 2011
Everywhere - 2017 Remaster
Under Pressure - Remastered 2011
There Is a Light That Never Goes Out - 2011 Remaster
Uptown Girl
Maneater
Summer Of '69
Heaven
You Shook Me All Night Long
Paradise City
Total Eclipse of the Heart
Into It
P*RNSTAR
R U Mine?
NUNCA MUDA?
10-Aug
Stephanie
Wild Ones (feat. Sia)
Waves - Robin Schulz Radio Edit
On The Floor
Blank Space
Classic
Stereo Hearts (feat. Adam Levine)
See You Again (feat. Charlie Puth)
Latch
Redbone
Don't Let Me Down
Grenade
Stay With Me
Use Somebody
Blame (feat. John Newman)
Ride
Needed Me
Can't Feel My Face
La La La
Juna
Bye Bye Bye - From Deadpool and Wolverine Soundtrack
Touch
BANDIT
Tú Con Él
SOMEBODY LOVES ME
CN TOWER
Lady Killers II
Disco
Embrace It
Balloon (feat. Doechii)
LO QUE LE PASÓ A HAWAii
Siren sounds (bonus)
MUTT
Good News
Forever Young
number one girl
Open Hearts
Dear god
Miss possessive
Chantaje (feat. Maluma)
PROVENZA
TQG
Antologia
I Can Do It With a Broken Heart
Love Me Harder
Into You
Disease
Wrecking Ball
Wannabe
Murder On The Dancefloor
Love You Like A Love Song
Believe
Oops!...I Did It Again
What's Up?
No Scrubs
Call Me Maybe
From The Start
bad guy
LoveDrug
Perfect Celebrity
360
because i liked a boy
Femininomenon
jealousy, jealousy
intro (end of the world)
LIKE WEEZY
TWIN TRIM (with Lil Uzi Vert)
OLYMPIAN
COCAINE NOSE
JUMPIN (with Lil Uzi Vert)
CRANK
Solcito
My Way
Bunga Abadi
Satu Bulan
Duka
She Will
Afsos
Just In Case
Bertaut
Serana
Isa lang
Human
Stargirl Interlude
Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) - Remix
Giza
I Hate Everything About You
Sugar
BEST INTEREST
No One Noticed (Extended Spanish)
Like I'm Gonna Lose You (feat. John Legend)
It Was A Good Day
No Idea
NEW MAGIC WAND
Work Out
Work Song
Me and the Devil
500lbs
Tumblr Girls (feat. Christoph Andersson)
Sahiba
Armed & Dangerous
Pesan Terakhir
ss
90210 (feat. Kacy Hill)
Coração Partido (Corazón Partío) - Ao Vivo
Salió El Sol
Monster
Running Wild
Vagabundo
BATTITO
Incoscienti Giovani
LA CURA PER ME
ball w/o you
check
MTG NA IMAGINAÇÃO - TOPO SESSIONS VOL. 1
Cópia Proibida
FANTASMA (versão GORDÃO DO PC)
Observando Essa Salada
Do Job
Rara Vez
EL AMOR DE SU VIDA
Amor de Vago
You'll Be in My Heart - Spotify Singles
Calm Down (with Selena Gomez)
Rewrite The Stars (with James Arthur & Anne-Marie)
Can't Help Falling in Love
My Girl
Silence
Burning Down (with Joe Jonas)
Save Your Tears (Remix) (with Ariana Grande) - Bonus Track
Bad Liar
Natural
When I'm With You
Nothing's New
オトノケ - Otonoke
Chk Chk Boom
Me Rehúso
Sola (Remix)
Amanece
Angelito
Unstoppable
Si No Estás
O Me Voy O Te Vas
Yo No Sé Mañana
Me Gustas Tu
Despacito
Me Dediqué a Perderte
Propuesta Indecente
Hey Mor
La Curiosidad
Kyoto
Bing Bong
Me Ha Costado
SORRY 4 THAT MUCH
una noche
NEL
MI EX TENÍA RAZÓN
BLANCA ROSITA Y MARIA
Orion
Tu Falta De Querer
Faded
Without You (feat. Sandro Cavazza)
Me, Myself & I
Are You With Me
I Took A Pill In Ibiza - Seeb Remix
Rollin' (Air Raid Vehicle)
Love Songs - Bonus
sining (feat. Jay R)
La Old Skul
Todo De Ti
Somethin’ ‘Bout A Woman (feat. Teddy Swims)
Sun to Me
Nine Ball
Angels Like You
Where's My Love
death bed (coffee for your head)
The Man Who Can't Be Moved
Sweet but Psycho
2002
28
It's My Life
Change (In the House of Flies)
Supermassive Black Hole
She Got the Best of Me
Chasin' You
Wind Up Missin’ You
Last Night
Pretty Slowly
Nice To Meet You
Bones
Enemy (with JID) - from the series Arcane League of Legends
Dancing In The Flames
Mrs Magic
Lover, You Should've Come Over
The Adults Are Talking
Always Forever
Home
Little Talks
Feel It Still
Stolen Dance
Line Without a Hook
Babydoll
A New Kind Of Love - Demo
SLOW DANCING IN THE DARK
Show Me How
Back On 74
PASSO BEM SOLTO - Slowed
Moth To A Flame (with The Weeknd)
Addicted
You & Me - Rivo Remix
I Only Smoke When I Drink
Again (feat. XXXTENTACION)
Lose Yourself
Robbery
Everybody Dies In Their Nightmares
Jocelyn Flores
SAD!
Empty Out Your Pockets
Sky
Runnin
Mmhmm
Superhero (Heroes & Villains) [with Future & Chris Brown]
GLORY
Give It To Me - Full Vocal Mix
Baby Don't Hurt Me
Vois sur ton chemin - Techno Mix
Overdrive (feat. Norma Jean Martine)
Jimmy Cooks (feat. 21 Savage)
Efecto
Ribs
Best Day Of My Life
Paris
Ghost Town
Mr. Jones
Knockin' On Heaven's Door
Santeria
Wind Of Change
Enter Sandman
Dreams
Torn
Piano Man
Don't Go Breaking My Heart
Bohemian Rhapsody - Remastered 2011
Sweet Home Alabama
Knockin' On Heaven's Door
My Love (feat. T.I.)
Dancing in the Moonlight
Hall of Fame (feat. will.i.am)
Where Is The Love?
Electric Feel
DARE
Somebody Told Me
Candy Shop
Womanizer
The Next Episode
Forever
Homecoming
Stan
Sexy Bitch (feat. Akon)
Don't You Worry Child - Radio Edit
Ni**as In Paris
Bored
Right My Wrongs
Exchange
Let It Happen
Girl With The Tattoo Enter.lewd
Nights
Kickstart My Heart
Cheri Cheri Lady
Another Day in Paradise - 2016 Remaster
You Make My Dreams (Come True)
With Or Without You
Smooth Operator - Single Version
Lovefool
anything
LoveHate Thing (feat. Sam Dew)
Good Feeling
Levels - Radio Edit
Rolling in the Deep
Pink Matter
Teenage Fever
Can I Be Him
Mercy
Often
Hey Brother
Galway Girl
dodger blue (feat. wallie the sensei, siete7x, roddy ricch)

In [12]:
taylors_version = df[df["artist_names"] == "Taylor Swift"]
taylors_version

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
93,94,Cruel Summer,1BxfuPKGuaTgP7aM0Bbdwr,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,89,2:58,0,8/23/2019,album,USUG11901472,10
361,362,cardigan,4R2kfaDFhslZEMJqAFNpdd,Taylor Swift,06HL4z0CvFAxyc27GXpf02,folklore,2fenSS68JI1h4Fo296JfGr,85,3:59,0,7/24/2020,album,USUG12002836,152
368,369,Lover,1dGr1c8CrMLDpV6mPbImSI,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,85,3:41,0,8/23/2019,album,USUG11901473,180
508,509,Don’t Blame Me,1R0a2iXumgCiFb7HEZ7gUE,Taylor Swift,06HL4z0CvFAxyc27GXpf02,reputation,6DEjYFkNZh67HP7R9PSZvv,84,3:56,0,11/10/2017,album,USCJY1750006,4
514,515,august,3hUxzQpSfdDqwM3ZTFQY0K,Taylor Swift,06HL4z0CvFAxyc27GXpf02,folklore,2fenSS68JI1h4Fo296JfGr,84,4:21,0,7/24/2020,album,USUG12002842,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9166,9167,Vigilante Shit,1xwAWUI6Dj0WGC3KiUPN0O,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Midnights,151w1FgRZfnKZA9FEcg9Z3,71,2:44,1,10/21/2022,album,USUG12205714,3
9168,9169,Dancing With Our Hands Tied,7I7JbDv63ZJJsSi24DyJrz,Taylor Swift,06HL4z0CvFAxyc27GXpf02,reputation,6DEjYFkNZh67HP7R9PSZvv,71,3:31,0,11/10/2017,album,USCJY1750012,3
9173,9174,I Think He Knows,2YWtcWi3a83pdEg3Gif4Pd,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,71,2:53,0,8/23/2019,album,USUG11901476,1
9174,9175,I Forgot That You Existed,43rA71bccXFGD4C8GOpIlN,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,71,2:50,0,8/23/2019,album,USUG11901471,1
9505,9506,Our Song,15DeqWWQB4dcEWzJg15VrN,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Taylor Swift,7mzrIsaAjnXihW3InKjlC3,70,3:21,0,10/24/2006,album,USCJY0703142,13

In [13]:
taylors_version = df[df["artist_names"].str.contains("Taylor Swift")]
taylors_version

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
93,94,Cruel Summer,1BxfuPKGuaTgP7aM0Bbdwr,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,89,2:58,0,8/23/2019,album,USUG11901472,10
361,362,cardigan,4R2kfaDFhslZEMJqAFNpdd,Taylor Swift,06HL4z0CvFAxyc27GXpf02,folklore,2fenSS68JI1h4Fo296JfGr,85,3:59,0,7/24/2020,album,USUG12002836,152
368,369,Lover,1dGr1c8CrMLDpV6mPbImSI,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,85,3:41,0,8/23/2019,album,USUG11901473,180
505,506,Fortnight (feat. Post Malone),2OzhQlSqBEmt7hmkYxfT6m,Taylor Swift|Post Malone,06HL4z0CvFAxyc27GXpf02|246dkjvS1zLTtiykXe5h60,THE TORTURED POETS DEPARTMENT,1Mo4aZ8pdj6L1jx8zSwJnt,84,3:48,0,4/18/2024,album,USUG12401028,8
508,509,Don’t Blame Me,1R0a2iXumgCiFb7HEZ7gUE,Taylor Swift,06HL4z0CvFAxyc27GXpf02,reputation,6DEjYFkNZh67HP7R9PSZvv,84,3:56,0,11/10/2017,album,USCJY1750006,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9166,9167,Vigilante Shit,1xwAWUI6Dj0WGC3KiUPN0O,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Midnights,151w1FgRZfnKZA9FEcg9Z3,71,2:44,1,10/21/2022,album,USUG12205714,3
9168,9169,Dancing With Our Hands Tied,7I7JbDv63ZJJsSi24DyJrz,Taylor Swift,06HL4z0CvFAxyc27GXpf02,reputation,6DEjYFkNZh67HP7R9PSZvv,71,3:31,0,11/10/2017,album,USCJY1750012,3
9173,9174,I Think He Knows,2YWtcWi3a83pdEg3Gif4Pd,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,71,2:53,0,8/23/2019,album,USUG11901476,1
9174,9175,I Forgot That You Existed,43rA71bccXFGD4C8GOpIlN,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Lover,1NAmidJlEaVgA3MpcPFYGq,71,2:50,0,8/23/2019,album,USUG11901471,1
9505,9506,Our Song,15DeqWWQB4dcEWzJg15VrN,Taylor Swift,06HL4z0CvFAxyc27GXpf02,Taylor Swift,7mzrIsaAjnXihW3InKjlC3,70,3:21,0,10/24/2006,album,USCJY0703142,13

In [16]:
other_artist = df[df["artist_names"] == "Tate McRae"]
other_artist

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
58,59,Revolving door,541sN2qNfIlllGn9nGOQoC,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,90,3:00,1,2/21/2025,album,USRC12403577,3
64,65,greedy,3rUGC1vUpkDG9CZFHMur1t,Tate McRae,45dkTj5sMRSjrmBSBeiHym,greedy,3UOV8XvCwMKaATRNXrYCjN,89,2:11,1,9/15/2023,single,USRC12301932,10
136,137,Sports car,2zOmS55knKWSgScYPTNmGQ,Tate McRae,45dkTj5sMRSjrmBSBeiHym,Sports car,1fOTqAU8mRMHlmOaHMqsge,87,2:45,0,1/24/2025,single,USRC12403580,6
365,366,you broke me first,4l0RmWt52FxpVxMNni6i63,Tate McRae,45dkTj5sMRSjrmBSBeiHym,TOO YOUNG TO BE SAD,1BaHo66NCQNx6ku0hPn9bR,85,2:50,1,3/26/2021,single,USRC12000832,31
801,802,exes,4E63weMCaNZuGPEFMnuEi8,Tate McRae,45dkTj5sMRSjrmBSBeiHym,THINK LATER,0OUOx6rJXtL66AzTnP9KUE,82,2:39,1,12/8/2023,album,USRC12302756,2
802,803,run for the hills,51hyZpbJlIgZIaX3TtMxmu,Tate McRae,45dkTj5sMRSjrmBSBeiHym,THINK LATER,0OUOx6rJXtL66AzTnP9KUE,82,2:23,1,12/8/2023,album,USRC12302981,6
949,950,Siren sounds (bonus),181yGUB8xEh4LfK8KhC4Wa,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,6KaEpgeZQF6ZVVAmSoZUrb,82,3:03,0,2/24/2025,album,USRC12500271,2
955,956,Dear god,2ETQsbiuGm2WLOSOr2I19A,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,82,2:51,0,2/21/2025,album,USRC12403579,3
956,957,Miss possessive,4Q9ExJGFgL9Jd9kmYH3nXs,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,82,2:19,1,2/21/2025,album,USRC12403576,2
1221,1222,It's ok I'm ok,3OfqwyE7RrZrtuxCRixfII,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,81,2:36,1,2/21/2025,album,USRC12402692,26
1222,1223,Purple lace bra,2bqLj0NvdtGbPCl9PdBtP2,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,81,3:11,0,2/21/2025,album,USRC12403552,3
1246,1247,she's all i wanna be,7l9IqDtVWJurTvkQHq1BGh,Tate McRae,45dkTj5sMRSjrmBSBeiHym,i used to think i could fly,5fhTetHew6Eph6HfQ9O5gJ,81,3:27,0,5/27/2022,album,USRC12103120,8
1955,1956,2 hands,0B7tnohfi83RQquo2JRHrL,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,79,3:02,1,2/21/2025,album,USRC12403001,9
2426,2427,Signs,6DDEfqOoLlasIbPdzboOu4,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,78,2:53,1,2/21/2025,album,USRC12403581,2
2757,2758,that way,7l97ElWmIdVHWUaOeeU5ZC,Tate McRae,45dkTj5sMRSjrmBSBeiHym,all the things i never said,1fK6nUQDMeIciyfhAADix8,77,2:55,0,1/24/2020,single,USRC11903528,14
3623,3624,Greenlight,56LQyaXsYWQZ2b7OPLAKEO,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,76,2:45,1,2/21/2025,album,USRC12403590,2
3624,3625,Means I care,63bgBHUBX1rutghlrXZrvp,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,76,2:55,1,2/21/2025,album,USRC12403589,2
4431,4432,Like I do,6jp9WjJtKF0Fgks0Y9Kkni,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,75,3:02,1,2/21/2025,album,USRC12403583,2
5353,5354,Nostalgia,1YZOcaGiN1cCwANvG3Ib9G,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,74,3:03,1,2/21/2025,album,USRC12403591,2
5354,5355,No I'm not in love,7a1D1K7sgFtumXN02ZdbUd,Tate McRae,45dkTj5sMRSjrmBSBeiHym,So Close To What,3w32SV56JvtJXsrYtThwzP,74,2:50,0,2/21/2025,album,USRC12403588,3
7716,7717,feel like shit,03zuGqxMwUFFmCwusq0WKE,Tate McRae,45dkTj5sMRSjrmBSBeiHym,i used to think i could fly,5fhTetHew6Eph6HfQ9O5gJ,72,3:23,1,5/27/2022,album,USRC12103112,2
7852,7853,uh oh,6qmvAJSUfVGMubvI2awW7p,Tate McRae,45dkTj5sMRSjrmBSBeiHym,uh oh,0m9hqW0RDEHPNXxhiFUGSq,71,2:49,1,9/30/2022,single,USRC12203443,1
8792,8793,hurt my feelings,4mFcwFOlSCxp6hjemRXwpd,Tate McRae,45dkTj5sMRSjrmBSBeiHym,THINK LATER,0OUOx6rJXtL66AzTnP9KUE,71,2:02,1,12/8/2023,album,USRC12302989,1

In [17]:
df.loc[(df["artist_names"].str.contains("Bruno Mars") & (df["popularity"] > 80))]

,rank,track_name,track_id,artist_names,artist_ids,album_name,album_id,popularity,duration,explicit,release_date,album_type,isrc,copies
0,1,Die With A Smile,2plbrEY59IikOBgBGLjaoe,Lady Gaga|Bruno Mars,1HY2Jd0NmPuamShAr6KMms|0du5cEVh5yTK9QJze8zA0C,Die With A Smile,10FLjwfpbxLmW8c25Xyc2N,100,4:11,0,8/16/2024,single,USUM72409273,9
7,8,APT.,5vNRhkKd0yEAg8suGBpjeY,ROSÉ|Bruno Mars,3eVa5w3URK5duf6eyVDbu9|0du5cEVh5yTK9QJze8zA0C,APT.,2IYQwwgxgOIn7t3iF6ufFD,95,2:49,0,10/18/2024,single,USAT22409172,1160
44,45,Locked out of Heaven,3w3y8KPTfNeOKPiqUTakBh,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Unorthodox Jukebox,58ufpQsJ1DS5kq4hhzQDiI,90,3:53,0,12/7/2012,album,USAT21203287,1165
63,64,When I Was Your Man,0nJW01T7XtvILxQgC5J7Wh,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Unorthodox Jukebox,58ufpQsJ1DS5kq4hhzQDiI,89,3:33,0,12/7/2012,album,USAT21206701,738
84,85,That's What I Like,0KKkJNfGyhkQ5aFogxQAPU,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,24K Magic,4PgleR09JVnm3zY1fW3XBA,89,3:26,0,11/17/2016,album,USAT21602948,546
96,97,Just the Way You Are,7BqBn9nzAq8spo5e7cZ0dJ,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Doo-Wops & Hooligans,1uyf3l2d4XYwiEqAb7t7fX,88,3:40,0,5/11/2010,album,USAT21001269,1340
160,161,Uptown Funk (feat. Bruno Mars),32OlwWuMpZ6b0aN2RZOeMS,Mark Ronson|Bruno Mars,3hv9jJF3adDNsBSIQDqcjp|0du5cEVh5yTK9QJze8zA0C,Uptown Special,3vLaOYCNCzngDf8QdBg2V1,87,4:29,0,1/12/2015,album,GBARL1401524,212
271,272,Talking to the Moon,161DnLWsx1i3u1JT05lzqU,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Doo-Wops & Hooligans,1uyf3l2d4XYwiEqAb7t7fX,85,3:37,0,5/11/2010,album,USAT21001985,629
493,494,24K Magic,6b8Be6ljOzmkOmFslEb23P,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,24K Magic,4PgleR09JVnm3zY1fW3XBA,84,3:45,0,11/17/2016,album,USAT21602944,641
568,569,It Will Rain,0M3HkE321xpCbCYqVKzr1q,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,It Will Rain,4A0vJtV9ok7vmr9ursSKj8,83,4:17,0,9/28/2011,single,USAT21102075,183
618,619,Fat Juicy & Wet,5M2lX0ZAYSAzCs1xPPi9BX,Sexyy Red|Bruno Mars,3DbwFQlvLxRSi2uX8mf81A|0du5cEVh5yTK9QJze8zA0C,Fat Juicy & Wet,1y2OfMwyaRDmtbQNl0DnQa,83,2:21,1,1/24/2025,single,USAT22500061,231
669,670,Marry You,6SKwQghsR8AISlxhcwyA9R,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Doo-Wops & Hooligans,6J84szYCnMfzEcvIcfWMFL,83,3:50,0,5/11/2010,album,USAT21001887,333
929,930,Grenade,4lLtanYk6tkMvooU0tWzG8,Bruno Mars,0du5cEVh5yTK9QJze8zA0C,Doo-Wops & Hooligans,6J84szYCnMfzEcvIcfWMFL,82,3:42,0,5/11/2010,album,USAT21001883,417

In [18]:
longest_songs = df.sort_values(by="duration", ascending=False)[["track_name", "artist_names", "duration"]]
longest_songs

,track_name,artist_names,duration
1989,White Noise Sleeping Aid to Help My Baby Fall ...,White Noise Baby Sleep,9:55
1547,Pyramids,Frank Ocean,9:52
2785,SWEET / I THOUGHT YOU WANTED TO DANCE (feat. B...,"Tyler, The Creator|Brent Faiyaz|Fana Hues",9:48
4445,Dancing Through Life,Jonathan Bailey|Ariana Grande|Ethan Slater|Mar...,9:47
4713,Shree Hanuman Chalisa,Hariharan,9:46
...,...,...,...
6489,Bonde do Brunão,Bruno Mars,0:57
7758,La Reina Presenta,KAROL G,0:54
7834,MONTAGEM VOZES PROFUNDAS - TikTok Version,DJ MAXZZ|DJ JL3 DA ZN|DJ CD 011,0:54
6664,I Said I Love You First,Selena Gomez|benny blanco,0:44
6663,Do You Wanna Be Perfect,Selena Gomez|benny blanco,0:37