Programming Activity 1

Create a DataFrame named temperatures that contains temperature readings for three people. Each person should have three temperature readings representing Morning, Afternoon, and Evening. Choose your own names and temperature values. Label the rows Morning, Afternoon, and Evening, then print the completed DataFrame.

In [2]:
import pandas as pd

temps_df = pd.read_csv(r"C:\Users\A02047803\Desktop\DATA_5500_FA_26\programming_activites\temperatures.csv")
temps_df

       Name   Morning   Afternoon   Evening
0      John        90          67        43
1  Jimmothy        80          80        80
2  John Too        34          35        36

In [5]:
temps_named = temps_df.set_index("Name")
temps_named.head()

          Morning  Afternoon  Evening
Name
John           90         67       43
Jimmothy       80         80       80
John Too       34         35       36

In [8]:
temps_named.loc["John"]

Morning      90
Afternoon    67
Evening      43
Name: John, dtype: int64